language: node_js
node_js:
  - 11

cache:
  npm: true
  directories:
    - node_modules

install:
  - npm i

script:
  - npm run test

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run test:cover
